CalculusProject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
urlpatterns = [
    path('signup/' , views.SignUpView.as_view() , name = 'signup'),
]

blog/urls.py
from django.urls import path
from .views import PostList, post_detail, add_favorite , FavoriteList
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('add_favorite/<str:user>/<int:post_id>', add_favorite, name='add_favorite'),
    # path('rem_favorite/<int:pk>/',remove_favorite,name='rem_favorite'),
    path('favorite-list/' , FavoriteList.as_view() , name ='favorite_list' ),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# from django.db import models
# from django.contrib.auth.models import AbstractUser
# # Create your models here.
#
# class CustomUser(AbstractUser):
#     age = models.PositiveIntegerField(null=True , blank = True)

blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    information_text = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)
    # users_like = models.ManyToManyField(User , related_name="users_like")
    html_content = models.TextField(blank=True)
    html_content_grad = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})



class Favoritepost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} -> {self.post.title}"
# python manage.py makemigrations
# python manage.py migrate

accounts/forms.py
# from django.contrib.auth.forms import UserCreationForm , UserChangeForm
# from .models import CustomUser
#
# class CustomUserCreationForm(UserCreationForm):
#     class Meta:
#         model = CustomUser
#         fields = ('username', 'email',)
#
# class CustomUserChangeForm(UserChangeForm):
#     class Meta:
#         model = CustomUser
#         fields = ('username', 'email',)

blog/forms.py
from django import forms

from .models import Post ,Favoritepost


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('favorite',)

# class FavoriteForm(forms.Form):
#     favorite = forms.BooleanField(required=False)

# from django import forms

# class AddToFavoritesForm(forms.Form):
#     book_id = forms.IntegerField(widget=forms.HiddenInput)

accounts/views.py
from django.views.generic import CreateView
# from .forms import CustomUserCreationForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
# Create your views here.

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

blog/views.py
from .models import Post ,Favoritepost
from django.views.generic import ListView , DeleteView
from django.shortcuts import get_object_or_404, render , redirect
from django.urls import reverse_lazy
from django.contrib import messages


class PostList(ListView):
    model = Post
    template_name = '../templates/post_list.html'
    context_object_name = "posts"
    paginate_by = 4
def add_favorite(request,user,post_id):
    post = get_object_or_404(Post, pk=post_id)
    Favoritepost.objects.create(user=request.user, post=post)
    post_favorite = Favoritepost.objects.filter(user=request.user, post=post)
    messages.success(request, "Added to favorites.")
    return redirect("blog:post_detail",post_id)


# def remove_favorite(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     favorite_post = Favoritepost.objects.filter(user=request.user, post=post)
#     if favorite_post.exists():
#         favorite_post.delete()
#         messages.success(request, "Removed from favorites.")
#     else:
#         messages.error(request, "This post was not in your favorites.")
#     return redirect("blog:post_detail", post_id)


class FavoriteList(ListView):
    model = Favoritepost
    template_name = 'post_favorite.html'
    context_object_name = 'post_f'
    paginate_by = 4



def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, '../templates/post_detail.html', {'post': post})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Calculus 3D</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    {#    <!-- fevicon -->#}
    {#    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif"/>#}
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
          media="screen">
</head>
<body>
<div class="popover-header footer_section layout_padding">

    <h1 class="font-weight-bold text-center subscribe_text " style="font-size: xxx-large">Calculus 3D</h1>

    <!-- banner section end -->
    <div class="navbar subscribe_text">
        <ul class="nav nav-tabs" id="myTab" role="tablist" style="margin: auto">
            <li class="nav-item">
                <a style="color: white" class="nav-link" href="{% url "blog:post_list" %}">Home</a>
            </li>
            <li class="nav-item">
                <a style="color: white" class="nav-link" href="{% url "blog:favorite_list" %}">My Favorites</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a style="color: white" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                       role="button"
                       aria-haspopup="true" aria-expanded="false">Your Account</a>
                    <div class="dropdown-menu">
                        <span class="dropdown-item-text text-capitalize " href="#">Hi {{ user.username }}</span>
                        <a class="dropdown-item text-capitalize" href="{% url "password_change" %}">Change Password</a>
                        <a style="color: #b40000" class="dropdown-item text-capitalize font-weight-bold "
                           href="{% url "logout" %}">Log out</a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item dropdown">
                    <a style="color: white" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                       role="button"
                       aria-haspopup="true" aria-expanded="false">Registration</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url "signup" %}">Sign Up</a>
                        <a class="dropdown-item" href="{% url "login" %}">Log in</a>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
{% block content %}
{% endblock %}

<div class="footer_section layout_padding">
    <img style="width: 150px ; height: 150px;float: left;margin-left: 150px" src="{% static 'images/math.png'%}">
    <img style="width: 150px ; height: 150px;float: right;margin-right: 150px" src="{% static 'images/ferd.png'%}">

    <div class="container">

        <div class="footer_main">
        </div>
        <a href="{% url 'signup' %}"><h1 class="subscribe_text">Signup Now</h1></a>

    </div>
</div>
<!-- footer section end -->
<!-- copyright section start -->
<div class="copyright_section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p class="copyright_text">© 2023 All Rights Reserved.<a href="https://html.design"> Ejlas </a></p>
            </div>
        </div>
    </div>
</div>
<!-- copyright section end -->
<!-- Javascript files-->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
<script src="{% static 'js/plugin.js' %}"></script>
<!-- sidebar -->
<script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<!-- javascript -->
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<script>
    $(document).ready(function () {
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });

        $(".zoom").hover(function () {

            $(this).addClass('transition');
        }, function () {

            $(this).removeClass('transition');
        });
    });
</script>
<script>
    function openNav() {
        document.getElementById("myNav").style.width = "100%";
    }

    function closeNav() {
        document.getElementById("myNav").style.width = "0%";
    }
</script>
</body>
</html>

templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="barber_section layout_padding">
        <div class="container-fluid">
            {% for message in messages %}
                <div class="text-center">
                    <div class="alert {{ message.tags }} alert-dismissible text-center"
                         style="color: #000000;background-color: #bbbbbb" role="alert">
                        <button type="button" class="close" data-dismiss="alert"
                                aria-label="Close">
                            <span aria-hidden="True">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                </div>
            {% endfor %}
            <main class="tm-main">
                <div class="text-center">
                        {{ post.html_content_grad|safe }}
                </div>
                <div class="col-lg-6" style="margin: auto">
                    <div class="mb-5">
                        <h1 style="font-size: xxx-large" class="font-weight-bold">{{ post.title|capfirst }}</h1>

                        <p dir="rtl">
                            {{ post.information_text|linebreaks }}
                        </p>

                        <div class="align-content-end" style="margin-left: -370px;">
                            {{ post.html_content|safe }}
                        </div>

                        {% if user.is_authenticated %}
                            <div class="subscribe_text font-weight-bold">
                                {% for post_ in post_f %}
                                    <p>ssss</p>
                                {% endfor %}
                                <a href="{% url 'blog:add_favorite' user.username post.id %}">Add to favorites</a>
                                <br>
                            </div>
                        {% else %}
                            <span class="caption">| You must log in to your account to save a post to favorites.  </span>
                            <a href="{% url 'login' %}">login</a> | <a href="{% url 'signup' %}">signup</a>
                        {% endif %}
                    </div>
                </div>
            </main>
        </div>
    </div>
{% endblock content %}

templates/post_favorite.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}My favorite curves{% endblock title %}
{% block content %}
    {% if user.is_authenticated %}

        <div class="barber_section layout_padding">
            <div class="container">
                {% if post_f %}


                    {% for post in post_f %}
                        {% if post.user.username ==  user.username %}
                            <div class="braber_taital_main">
                                <div class="row">
                                    <div>
                                        <div class="barber_bg_main">
                                            <div class="text-center">
                                                <div class="fashion_img">
                                                    <img src="{{ post.post.image.url }}">
                                                </div>
                                            </div>
                                            <h1 class="barber_taital">{{ post.post.title|capfirst }}</h1>
                                            <p class="barber_text">{{ post.post.information_text|truncatewords:90 }}</p>
                                            <div class="blogr_right">
                                                <a href="{% url 'blog:post_detail' post.post.id %}"
                                                   class="btn btn-custom font-weight-bold text-center ">Read
                                                    More!</a>
                                            </div>
                                        </div>
                                    </div>
                                    {#////////////////////////////////#}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="navbar subscribe_text">
                        <nav aria-label="Page navigation example" style="margin: auto">
                            <ul class="pagination justify-content-end">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                           tabindex="-1">Previous</a>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:-1 }}</a>
                                    </li>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                                    </li>
                                {% endif %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a>
                                </li>
                                {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.next_page_number }}">{{ page_obj.number|add:1 }}</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                           tabindex="-1">Next</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" href="#" tabindex="-1">Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                {% else %}
                    <div style="margin-top: 135px" class=" subscribe_text">
                        <h1 class="caption">Your Favorite List is empty </h1>
                    </div>
                    <div class="subscribe_text">
                        <h1 style="color: white">---------------------------------------------------------------</h1>
                        <h1 style="color: white">---------------------------------------------------------------</h1>
                    </div>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div style="margin-top: 180px" class=" subscribe_text">
            <h1 class="caption">You must log in to your account to save a post to favorites. </h1>
            <a href="{% url 'login' %}">login</a> | <a href="{% url 'signup' %}">signup</a>
        </div>
        <div class="subscribe_text">
            <h1 style="color: white">---------------------------------------------------------------</h1>
            <h1 style="color: white">---------------------------------------------------------------</h1>
            <h1 style="color: white">---------------------------------------------------------------</h1>
            <h1 style="color: white">---------------------------------------------------------------</h1>
        </div>
    {% endif %}

{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Curves{% endblock title %}
{% block content %}
    <div class="barber_section layout_padding">
        <div class="container">
            {% for post in posts %}
                <div class="braber_taital_main">
                    <div class="row">

                        <div>
                            <div class="barber_bg_main">
                                <div class="text-center">
                                    <div class="fashion_img">
                                        <img src="{{ post.image.url }}">
                                    </div>
                                </div>
                                <h1 class="barber_taital">{{ post.title|capfirst }}</h1>
                                <p class="barber_text">{{ post.information_text|truncatewords:90 }}</p>
                                <div class="blogr_right">
                                    <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-custom font-weight-bold text-center ">Read
                                        More!</a>
                                </div>
                            </div>
                        </div>
                        {#////////////////////////////////#}
                    </div>
                </div>
            {% endfor %}
            <div class="navbar subscribe_text">
                <nav aria-label="Page navigation example" style="margin: auto">
                    <ul class="pagination justify-content-end">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:-1 }}</a></li>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                        {% endif %}
                        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number|add:1 }}</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock content %}